### ISSUE TITLE
Missing "paymentMethod" in Invoice entity

### ISSUE THREAD

**Issue by tqthy** [tqthy/Furniture-Store-Management-BE#17]
I need it in order to implement feature getPaymentMethodStatistic and QR code payment

**Comment by Tam-Vu** [comment]
run this in local database to add column "paymentMethod" without losing created data:
create type enum_Invoice_paymentMethod as enum ('Cash', 'QR code');
ALTER TABLE "Invoice" ADD COLUMN "paymentMethod" enum_Invoice_paymentMethod;
